#staging
# url: http://jellekuiper.sven

#production
url: https://jellekuiper.nl

name: "Jelle Kuiper"
title: "De leukste trouwambtenaar!"
description: "Jelle Kuiper, de leukste trouwambtenaar, cabaretier en theaterproducent."
language: 'nl/nl'
keywords: "Jelle Kuiper, de leukste trouwambtenaar, cabaretier en theaterproducent."
author:
  name: jellekuiper
  email: info@jellekuiper.nl
  bio:  "Strategisch adviesbureau voor zorgondernemers."
  twitter:  Jelle_Kuiper
encoding: utf-8
timezone: Europe/Amsterdam

# folders
baseurl:
source: ./app/
destination: ./dist
assets:
  compress:
    css: true
    js: true
exclude: [
          'assets/modules',
          'assets/sass',
          'assets/original-img'
          ]
keep_files: ['img', 'pdf']

# _config.build.yml sets future and show_drafts to false on `gulp build`
future: true
show_drafts: true

disqus:
  shortname: 'jellekuiper'

permalink: /:path
collections:
  theaterproducties:
    permalink: /theaterproducties/:path
    output: true

defaults:
  - scope:
      path: '' # empty string for all files
    values:
      layout: 'page'
      opengraph: 'opengraph.png'
  - scope:
      path: ''
      type: 'theaterproducties'
    values:
      layout: 'detailpage'