# Jekyll configuration precedence:
# 1. gulp task
# 2. config.build.yml
# 3. config.yml

name: "Jelle Kuiper | Trouwambtenaar"
description: "Voor een leuke trouwdag"
url: https://webnozems.nl
keywords: "trouwen jellekuiper jelle kuiper amsterdam"
author:
  name: jellekuiper
  email: info@jellekuiper.nl
  bio:  "Strategisch adviesbureau voor zorgondernemers."
  twitter:  Jelle_Kuiper
encoding: utf-8
timezone: Europe/Amsterdam

# folders
baseurl: 
source: ./app/
destination: ./dist
assets:
  compress:
    css: true
    js: true
exclude: [
          'assets/modules',
          'assets/scss',
          'assets/original-img'
          ]
include: []
keep_files: ['img', 'pdf']

# _config.build.yml sets future and show_drafts to false on `gulp build`
future: true
show_drafts: true

disqus:
  shortname: 'jellekuiper'

# Markdown library
markdown: redcarpet
#   extensions: ['fenced_code_blocks', 'smart']

permalink: /:path/

collections:
  pages:
    permalink: /:path/
    output: true
  posts:
    permalink: /theaterproducties/:path/
    output: true

defaults:
  - scope:
      path: "" # empty string for all files
    values:
      layout: "page"
      weight: 0
      opengraph: 'opengraph.png'
